version: '3.8'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adams-zone-local
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
